version: "3.9"

# a common network within which every container will be operating
networks:
  common_network:
    driver: bridge

# data volumes for containers
volumes:
  db_data:
    driver: local
  pgadmin_data:
    driver: local

# configurations for every containerized service are listed here
services:
  # a common database server
  db:
    container_name: db
    image: postgres:13-alpine
    networks:
      - common_network
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    volumes:
      - db_data:/var/lib/postgresql/data

  # pgadmin4 for administering all databases
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    networks:
      - common_network
    restart: always
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_LISTEN_PORT}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # auth-service
  auth:
    container_name: auth
    image: anhdau185/auth-service:latest
    networks:
      - common_network
    restart: always
    ports:
      - "${AUTH_APIS_PORT}:${AUTH_APIS_PORT}"
    depends_on:
      - db
    links:
      - db
